const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');
const {sample}=require('../game/measurement.js');
const outcomes=[[1,1],[-1,1],[0,-1]],probabilities=[.4,.1,.5];
assert.deepEqual(sample([1],[[1,1]],100),[1,1]);
assert.throws(()=>sample(probabilities,outcomes,0));
let seed=3;const rng=()=>((seed=(1664525*seed+1013904223)>>>0)/4294967296);
let sum=0,sumsq=0,sumB=0,sumAB=0,N=20000;
for(let i=0;i<N;i++){
  const [a,b]=sample(probabilities,outcomes,100,rng);sum+=a;sumsq+=a*a;sumB+=b;sumAB+=a*b;
  assert.ok(Math.abs(a)<=1&&Math.abs(b)<=1);
}
assert.ok(Math.abs(sum/N-.3)<.003);
assert.ok(Math.abs(sumsq/N-(sum/N)**2-.0041)<.00025);
assert.ok(Math.abs(sumAB/N-(sum/N)*(sumB/N)-.003)<.00025);
const elements={};const handlers={};const windowHandlers={};
let boardBounds={left:0,top:0,width:720,height:560};
const context2d=new Proxy({measureText:()=>({width:30})},{get:(o,k)=>o[k]??(()=>{})});
function element(id){return elements[id]??=( {children:[],style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},appendChild(x){this.children.push(x)},remove(){},scrollIntoView(){},setAttribute(){},getContext:()=>context2d,width:720,height:560,addEventListener:(name,fn)=>{handlers[name]=fn},getBoundingClientRect:()=>boardBounds});}
const timers=[];
const preferences=new Map();
const scope={console,Math,Date,setTimeout:fn=>{timers.push(fn);return timers.length},localStorage:{getItem:key=>preferences.get(key)??null,setItem:(key,value)=>preferences.set(key,String(value))},document:{getElementById:element,createElement:()=>element(Math.random())},window:{devicePixelRatio:2,addEventListener:(name,fn)=>{windowHandlers[name]=fn}}};
vm.createContext(scope);
vm.runInContext(fs.readFileSync('game/dataset.js','utf8'),scope);
vm.runInContext(fs.readFileSync('game/measurement.js','utf8'),scope);
vm.runInContext(fs.readFileSync('game/memes.js','utf8'),scope);
vm.runInContext(fs.readFileSync('game/popeye-memes.js','utf8'),scope);
vm.runInContext(fs.readFileSync('game/famous-memes.js','utf8'),scope);
let source=fs.readFileSync('game/index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
vm.runInContext(source,scope);
vm.runInContext('memesOn=false;',scope);
const read=code=>vm.runInContext(code,scope);
async function drain(){
  while(timers.length){timers.shift()();await Promise.resolve();}
}
async function main(){
  assert.equal(elements.board.width,1440,'retina bitmap has two pixels per CSS pixel');
  assert.equal(elements.board.height,1120);
  // The first visit starts with a guided three-scan clean-map round.
  assert.equal(read('firstVoyage'), true);
  assert.equal(read('view.b0'), 0);
  assert.equal(read('view.b1'), 23);
  assert.equal(read('shots'), 100);
  assert.equal(elements.firstGuide.hidden, false);
  assert.equal(elements.reveal.disabled, true);
  read('shots=20');
  read('ping(kLo(),hLo())');
  assert.equal(read('shots'), 100);
  read('newRound()');
  // Existing gameplay regression coverage uses the full controls after dismissing the first-voyage guide.
  elements.skipIntro.onclick();
  // Resizing and changing screen density preserve data coordinates and drag hit targets.
  const resizeView=read('JSON.stringify(view)');
  const resizeHandles=read('JSON.stringify(handles)');
  boardBounds={left:35,top:80,width:320,height:340};
  scope.window.devicePixelRatio=3;
  windowHandlers.resize();
  assert.equal(elements.board.width,960);assert.equal(elements.board.height,1020);
  assert.equal(read('JSON.stringify(view)'),resizeView);
  assert.equal(read('JSON.stringify(handles)'),resizeHandles);
  assert.ok(Math.abs(read('toK(px((kLo()+kHi())/2))-(kLo()+kHi())/2'))<1e-12);
  assert.ok(Math.abs(read('toH(py((hLo()+hHi())/2))-(hLo()+hHi())/2'))<1e-12);
  const handlePoint=read('({x:px(kLo()+handles[2].t*(kHi()-kLo())),y:py(handles[2].h)})');
  handlers.pointerdown({clientX:boardBounds.left+handlePoint.x,clientY:boardBounds.top+handlePoint.y});
  assert.equal(read('drag===handles[2]'),true,'scaled canvas handles use CSS-pixel hit targets');
  const targetH=read('hLo()+.7*(hHi()-hLo())');
  handlers.pointermove({clientX:boardBounds.left+handlePoint.x,clientY:boardBounds.top+read(`py(${targetH})`)});
  assert.ok(Math.abs(read('handles[2].h')-targetH)<1e-12);
  windowHandlers.pointerup();
  // A resized click samples the intended grid point, independent of DPR and page position.
  const samplePoint=read('({k:data.kappas[view.b0+2],h:data.hs[view.a0+2]})');
  handlers.pointerdown({clientX:boardBounds.left+read(`px(${samplePoint.k})`),clientY:boardBounds.top+read(`py(${samplePoint.h})`)});
  assert.equal(read('pings.length'),1);
  assert.ok(Math.abs(read('pings[0].k')-samplePoint.k)<1e-12);
  assert.ok(Math.abs(read('pings[0].h')-samplePoint.h)<1e-12);
  boardBounds={left:0,top:0,width:720,height:560};scope.window.devicePixelRatio=2;
  windowHandlers.resize();elements.reset.onclick();
  const initial=read('JSON.stringify(view)');
  read('shots=20');
  const run=elements.agent.onclick();
  assert.equal(read('aiRunning'),true);
  assert.equal(read('pings.length'),1,'first scan must appear before the next animation frame');
  assert.match(elements.aiStatusTitle.textContent,/AI scanning/);
  assert.equal(elements.agent.disabled,true);
  assert.equal(elements.reveal.disabled,true);
  // Repeated clicks and player actions cannot alter an AI run.
  await elements.agent.onclick();
  read('ping(kLo(),hLo())');
  handlers.pointerdown({clientX:200,clientY:200});
  elements.reveal.onclick();
  assert.equal(read('pings.length'),1);
  assert.equal(read('revealed'),false);
  await drain();await run;
  assert.equal(read('JSON.stringify(view)'),initial);
  assert.equal(read('aiRunning'),false);
  assert.equal(read('aiPreview'),true);
  assert.equal(read('energy'),0);
  assert.equal(read('pings.length'),45,'keep AI scans visible after finishing');
  assert.equal(read('shots'),100,'AI preview shows the power used by its scans');
  assert.equal(elements.takeTurn.hidden,false);
  const target=read('agentScore');assert.ok(target>=0&&target<=1);
  assert.match(elements.aiStatusTitle.textContent,/AI finished/);
  assert.match(elements.aiStatusDetail.textContent,/45 scans/);
  const aiHandles=read('JSON.stringify(handles)');
  handlers.pointerdown({clientX:200,clientY:200});elements.template.onclick();elements.reveal.onclick();
  assert.equal(read('JSON.stringify(handles)'),aiHandles);
  assert.equal(read('revealed'),false,'AI demo must not be submitted as a human score');
  elements.takeTurn.onclick();
  assert.equal(read('agentScore'),target);
  assert.equal(read('JSON.stringify(view)'),initial);
  assert.equal(read('energy'),90);assert.equal(read('pings.length'),0);
  assert.equal(read('aiPreview'),false);assert.equal(elements.reveal.disabled,false);
  assert.equal(read('shots'),20,'restore the player scan power at handoff');
  elements.reset.onclick();assert.equal(read('agentScore'),target);
  read('shots=100; ping(kLo(),hLo())');assert.equal(read('energy'),88);
  elements.reveal.onclick();assert.equal(read('revealed'),true);
  assert.match(elements.sheet.innerHTML,/AI/,'human result retains AI comparison');
  const before=read('JSON.stringify(handles)');
  handlers.pointerdown({clientX:200,clientY:200});elements.template.onclick();
  assert.equal(read('JSON.stringify(handles)'),before);assert.equal(read('pings.length'),1);
  elements.newMap.onclick();assert.equal(read('agentScore'),null);assert.equal(read('revealed'),false);
  // Cancelling an in-flight animation must not write into the replacement round.
  const cancelled=elements.agent.onclick();assert.equal(read('pings.length'),1);
  elements.newMap.onclick();
  const newView=read('JSON.stringify(view)');
  await drain();await cancelled;
  assert.equal(read('JSON.stringify(view)'),newView);assert.equal(read('pings.length'),0);
  assert.equal(read('energy'),90);assert.equal(read('agentScore'),null);
  assert.equal(read('aiRunning'),false);assert.equal(elements.agent.disabled,false);
  // Hunter mode has 60 energy, hence exactly 30 solid scans.
  read('mode="hunter";newRound()');
  const hunter=elements.agent.onclick();await drain();await hunter;
  assert.equal(read('pings.length'),30);assert.equal(read('energy'),0);
  elements.takeTurn.onclick();assert.equal(read('energy'),60);assert.equal(read('pings.length'),0);
  assert.ok(!source.includes('truth ${'));
  // Every automatic pack combination, plus explicit previews, must honor its switches.
  read('memesOn=true;useClips=true;famousOn=true;mixedMemeCount=0');
  assert.equal(read('chooseReaction("reveal_high")'),'famous_reveal_high');
  assert.equal(read('chooseReaction("reveal_high")'),'reveal_high');
  assert.match(read('art("reveal_high")'),/clips\/cards\/reveal_high.webm/);
  assert.match(read('art("famous_reveal_high")'),/ronaldo.gif/);
  elements.clips.onclick();
  assert.equal(read('useClips'),false);
  assert.equal(read('chooseReaction("reveal_high")'),'famous_reveal_high');
  assert.equal(elements.testMeme.disabled,true);
  elements.famous.onclick();
  assert.equal(read('chooseReaction("reveal_high")'),'popeye_reveal_high');
  elements.clips.onclick();
  assert.equal(read('chooseReaction("reveal_high")'),'reveal_high');
  assert.equal(read('chooseReaction("first_ping")'),'popeye_first_ping');
  elements.clips.onclick();elements.popeye.onclick();
  assert.equal(read('chooseReaction("reveal_high")'),'reveal_high');
  assert.ok(!read('art("reveal_high")').includes('<video'));
  scope.window.matchMedia=()=>({matches:true});
  assert.match(read('art("famous_reveal_high")'),/ronaldo.png/);
  read('useClips=true');
  assert.ok(!read('art("reveal_high")').includes('autoplay'));
  elements.memes.onclick();
  const count=elements.cards.children.length;
  read('react("first_ping", "", true)');
  assert.equal(elements.cards.children.length,count);
  read('showResult("reveal_high",.97)');
  assert.ok(!elements.sheet.innerHTML.includes('big-art'));
  assert.match(elements.sheet.innerHTML,/Your expedition results/);
  assert.match(elements.sheet.innerHTML,/Targeted scans/);
  assert.equal(elements.previewFamous.disabled,true);
  // Rotating variants retain their event's lesson; previews don't advance rotation.
  const variant1=read('FAMOUS_REACTIONS.choose("repeat_changed")');
  const variant2=read('FAMOUS_REACTIONS.choose("repeat_changed")');
  assert.notEqual(variant1,variant2);
  assert.equal(read('FAMOUS_REACTIONS.choose("repeat_changed")'),variant1);
  assert.equal(read(`reactionLesson(${JSON.stringify(variant1)})`),read(`reactionLesson(${JSON.stringify(variant2)})`));
  assert.equal(read('FAMOUS_REACTIONS.previews.length'),12);
  const previewFiles=read('FAMOUS_REACTIONS.previews.map(e=>FAMOUS_REACTIONS.art(FAMOUS_REACTIONS.byEvent[e]).match(/src="([^"]+)"/)[1])');
  assert.equal(new Set(previewFiles).size,12);
  for(const file of previewFiles) assert.ok(fs.existsSync('game/'+file));
  // A lucky no-scan guess must never receive a victory GIF.
  read('pings=[];agentScore=.8;lastAttempt=null');
  assert.equal(read('resultEvent(1,70,0)'),'no_scans');
  read('pings=[{}];agentScore=null');
  assert.equal(read('resultEvent(.9,85,20)'),'personal_best');
  assert.equal(read('resultEvent(.9,null,20)'),'reveal_mid');
  assert.equal(read('resultEvent(.98,85,20)'),'reveal_high');
  read('agentScore=.8');assert.equal(read('resultEvent(.9,85,20)'),'beat_agent');
  read('agentScore=null;lastAttempt={score:.87,spent:20};mode="hunter"');
  assert.equal(read('resultEvent(.82,90,50)'),'overspend');
  assert.notEqual(read('resultEvent(.82,90,20)'),'overspend');
  read('newRound()');assert.equal(read('lastAttempt'),null);
  // With famous GIFs disabled, the six new events still have valid fallback artwork.
  read('famousOn=false;useClips=false');
  for(const event of ['ai_start','repeat_changed','overspend','personal_best','tutorial_milestone','no_scans']) {
    assert.ok(read(`art(chooseReaction(${JSON.stringify(event)}))`).length);
  }
  // Presentation is temporary: entering from a different stage/mode restores user preferences on exit.
  read('mode="hunter";stage=2;shots=500;memesOn=true;syncMode();syncMemeControls();newRound()');
  elements.presentationDemo.onclick();
  assert.equal(read('demoMode'),true);assert.equal(read('mode'),'practice');
  assert.equal(read('stage'),0);assert.equal(read('shots'),100);assert.equal(read('memesOn'),false);
  assert.equal(read('energy'),90);assert.equal(elements.demoGuide.hidden,false);
  assert.equal(preferences.get('ph_mode'),'hunter','demo must not persist its temporary mode');
  assert.equal(preferences.get('ph_meme_all'),'on','demo must not persist its temporary quiet preference');
  const fixedView=read('JSON.stringify(view)');
  assert.equal(fixedView,read('JSON.stringify({b0:0,b1:data.grid-1,a0:0,a1:data.grid-1})'));
  elements.levels.children[2].onclick();elements.shots.children[0].onclick();
  elements.modes.onclick({target:{closest:()=>({dataset:{mode:'hunter'}})}});
  assert.equal(read('stage'),0);assert.equal(read('shots'),100);assert.equal(read('mode'),'practice');
  assert.ok(elements.shots.children.every(button=>button.disabled),'fixed presentation scan power is locked');
  read('ping(data.kappas[3],data.hs[4])');
  const firstDemoScan=read('JSON.stringify(pings[0])');
  elements.reset.onclick();read('ping(data.kappas[3],data.hs[4])');
  assert.equal(read('JSON.stringify(pings[0])'),firstDemoScan,'retry uses the same measurement seed');
  elements.compareView.onclick();
  assert.equal(elements.gameView.hidden,true);assert.equal(elements.comparisonView.hidden,false);
  elements.playView.onclick();
  assert.equal(elements.gameView.hidden,false);assert.equal(elements.comparisonView.hidden,true);
  assert.equal(read('JSON.stringify(pings[0])'),firstDemoScan,'switching views preserves a player run');
  elements.reset.onclick();
  read('for(let i=0;i<46;i++)ping(kLo(),hLo())');
  assert.equal(read('pings.length'),45,'a player cannot exceed the fixed demo budget');
  assert.equal(read('energy'),0);assert.equal(elements.totalShots.textContent,'4,500');
  elements.reveal.onclick();
  assert.match(elements.sheet.innerHTML,/Restart demo/);
  assert.ok(!elements.sheet.innerHTML.includes('id="next"'),'demo results cannot advance to another stage');
  elements.newMap.onclick();
  assert.equal(read('JSON.stringify(view)'),fixedView);assert.equal(read('pings.length'),0);
  const demoRun=elements.agent.onclick();await drain();await demoRun;
  assert.equal(read('pings.length'),45);assert.equal(elements.totalShots.textContent,'4,500');
  const demoScore=read('agentScore');
  elements.compareView.onclick();elements.playView.onclick();
  assert.equal(read('aiPreview'),true,'a finished AI map survives a comparison visit');
  assert.equal(read('agentScore'),demoScore);
  elements.takeTurn.onclick();
  assert.equal(read('energy'),90);assert.equal(read('shots'),100);assert.equal(read('agentScore'),demoScore);
  read('ping(data.kappas[3],data.hs[4])');
  assert.equal(read('JSON.stringify(pings[0])'),firstDemoScan,'the player handoff restores the demo seed');
  const interruptedDemo=elements.agent.onclick();
  elements.compareView.onclick();
  await drain();await interruptedDemo;
  assert.equal(read('aiRunning'),false);assert.equal(read('pings.length'),0);assert.equal(read('energy'),90);
  assert.equal(read('agentScore'),null,'changing views cannot leave a partial AI target');
  elements.playView.onclick();
  const exitingDemo=elements.agent.onclick();
  elements.presentationDemo.onclick();
  await drain();await exitingDemo;
  assert.equal(read('demoMode'),false);assert.equal(elements.demoGuide.hidden,true);
  assert.equal(read('mode'),'hunter');assert.equal(read('stage'),2);assert.equal(read('shots'),500);
  assert.equal(read('memesOn'),true);assert.equal(preferences.get('ph_meme_all'),'on');
  assert.equal(read('energy'),60);assert.equal(read('pings.length'),0);assert.equal(read('aiRunning'),false);
  assert.ok(elements.shots.children.every(button=>!button.disabled),'normal scan power controls unlock after demo');
  console.log('Expanded pack tests passed: 12 unique previews, rotation, contextual lessons, milestone selection, and fallback coverage.');
  console.log('Meme tests passed: mixed/personal/famous/fallback routing, all-off results, quiet popups, and reduced-motion assets.');
  console.log('Game tests passed: visible AI progress, persistent demo, explicit player handoff, 45/30 scans, cancellation, locked AI scoring, and preserved rematches.');
  console.log('Canvas tests passed: DPR backing resolution, viewport resize invariance, scan coordinates, and handle dragging after resize.');
  console.log('Presentation tests passed: fixed map and shot budget, repeatable measurements, AI handoff/cancellation, view switching, and preference restoration.');
}
main().catch(error=>{console.error(error);process.exitCode=1});
